# This is a basic workflow to help you get started with Actions

name: Terraform Apply 

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-22.04
    environment: ${{github.ref_name}}
  
    name: "Terraform Apply"
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

    steps:
      - uses: actions/checkout@v4

      # Applies the Terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve "${{github.ref_name}}.tfplan"
