name: Deploy REST API

on:
  workflow_dispatch:
  
env:
  WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref_name }}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
  go:
    name: Go Setup
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Go Repository'
        id: checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: 'main'
          repository: 'simonhoumb/gutendex-api.git'
  
      - name: Setup Go
        id: setup_go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
  
      - name: Go Test
        id: go_test
        run: go test ./... --race
        working-directory: 'cmd'
        shell: bash
  
      - name: Build
        id: build
        run: go build main.go
        working-directory: 'cmd'
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: cmd  

  azure:  
    needs: [go]
    name: Deploy to Azure Web App
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: app-binary
        path: cmd
    
    - name: Azure Login
      id: az_login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Deploy to Azure Web App
      id: deploy_to_webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "web-simonhou-oppg2-${{env.WORKSPACE}}"
        slot-name: 'webslot'
        package: 'cmd'
