# This is a basic workflow to help you get started with Actions

name: Terraform Linting

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: "Linting"
    runs-on: ubuntu-22.04

    # Sets up the environments used
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.53.0

      # Shows tflint version
      - name: Show version
        id: version
        run: tflint --version

      # Runs 'tflint'
      - name: Run tflint
        id: tflint
        run: tflint --recursive --minimum-failure-severity error
