name: Terraform Security Check
on:
  push:
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with: 
          # Excludes all LOW severities.
          additional_args: --minimum-severity MEDIUM 
