# This is a basic workflow to help you get started with Actions

name: Validate Infrastructure

# Controls when the workflow will run
on: 
  push:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: "Validate"
    runs-on: ubuntu-22.04

    # Sets up the environments used
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

    steps:
      - uses: actions/checkout@v4

      # Runs 'terraform init'
      - name: Terraform init
        id: init
        run: terraform init

      # Runs 'terraform validate'
      - name: Terraform validate
        id: validate
        run: terraform validate
